### ISSUE TITLE
Verwendung des Makros in Citavi 6.5.0.0

### ISSUE THREAD

**Issue by QRiousKat** [Jay-Squared/QuotationsToolbox#15]
Hallo J²,

die Makro-Sammlung scheint genau das zu sein, was Citavi "vollendet". Vielen Dank dafür. Leider bekomme ich es nicht zum laufen. 
Ich habe die *.dll-Datei (heruntergeladen hier: https://help.citavi.com/topic/annotationen-automatisch-umwandeln-wissenselemente-verbinden-wissenselemente-nummerieren) in den Ordner C:\Program Files (x86)\Citavi 6\AddOns gelegt (den AddOns-Ordner musst ich zunächst anlegen). Den Code habe ich von GitHub als Zip herunter geladen, extrahiert und ebenfalls in den AddOn-Ordner gelegt. Wenn ich versuche, eine der *.cs-Dateien im Makro-Editor von Citavi auszuführen erhalte ich jeweils eine Fehlermeldung:

![grafik](https://user-images.githubusercontent.com/68898789/93709969-23c95880-fb43-11ea-9ec9-326746723c1e.png)

Der Name der nicht auffindbaren *.dll-Datei variiert dabei, je nach Makro, das ich auszufürhen versuche.
Was mache ich falsch? Ich würde mich sehr freuen, das irgendwie benutzen zu können.

Vielen Dank im Voraus und viele Grüße

**Comment by Jay-Squared** [comment]
Das AddOn ist ganz unabhängig von den Makros. Die laufen separat voneinander. Um welche Makros handelt es sich eigentlich konkret? Die Word-Makros laufen ja etwa nur in Word, ein paar Skripte sind für den Zitationsstileditor, und eigentlich kann man nur dieses [Skript ](https://github.com/Jay-Squared/CitaviKnowledgeItemScripts) hier Standalone ausführen, da ist dann aber auch egal, wo man es speichert (wahrscheinlich sogar besser, es nicht im Programmordner zu speichern.)

**Comment by Jay-Squared** [comment]
Ich schließe dieses Ticket, da ich das Problem aufgrund der Beschreibung nicht reproduzieren kann.

**Comment by Jay-Squared** [comment]
Ich schließe dieses Ticket, da ich das Problem aufgrund der Beschreibung nicht reproduzieren kann.
