### ISSUE TITLE
Addon für Citavi 5 verwendbar?

### ISSUE THREAD

**Issue by papatistos** [Jay-Squared/QuotationsToolbox#18]
Besteht die Möglichkeit dieses Add-on auch unter Citavi 5 zum Laufen zu bringen? Ich habe die dll dort in den bin ordner gespeichert, das Add-on wird an dieser Stelle aber nicht erkannt...

**Comment by papatistos** [comment]
OK, ich habe jetzt verstanden, dass man das Addon-Verzeichnis selbst erstellen muss. Das habe ich nun getan und Citavi findet das Addon, produziert aber untenstehende Fehlermeldung. Ich poste das hier mal, falls es ohne grösseren Aufwand möglich sein sollte das Addon kompatibel zu machen.

<Falls möglich, beschreiben Sie hier bitte kurz, was Sie vor dem Fehler gemacht haben.>

--------------------------------------------------

Technische Informationen für den Citavi-Support:

System.MissingMethodException: Methode nicht gefunden: "SwissAcademic.Citavi.LinkedResource SwissAcademic.Citavi.Location.get_Address()".
   bei QuotationsToolbox.PDFUtilities.GetPDFLocations(KnowledgeItem knowledgeItem)
   bei QuotationsToolbox.UI.GoToQuotationAdornmentCanvasses(KnowledgeItem quotation)
   bei QuotationsToolbox.UI.QuotationSmartRepeater_ActiveListItemChanged(Object o, EventArgs a)
   bei SwissAcademic.Citavi.Shell.Controls.SmartRepeaters.SmartRepeater`1.OnActiveListItemChanged(EventArgs e)
   bei SwissAcademic.Citavi.Shell.Controls.SmartRepeaters.SmartRepeater`1.set_ActiveListItem(T value)
   bei SwissAcademic.Citavi.Shell.Controls.SmartRepeaters.SmartRepeater`1.row_SubControlMouseDown(Object sender, SmartRepeaterRowMouseEventArgs`1 e)
   bei SwissAcademic.Citavi.Shell.Controls.SmartRepeaters.SmartRepeaterRow`1.OnControlMouseDown(SmartRepeaterRowMouseEventArgs`1 e)
   bei SwissAcademic.Citavi.Shell.Controls.SmartRepeaters.SmartRepeaterRow`1.control_MouseDown(Object sender, MouseEventArgs e)
   bei System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   bei SwissAcademic.Citavi.Shell.Controls.SmartRepeaters.QuotationSmartRepeaterRow.OnMouseDown(MouseEventArgs e)
   bei System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

--------------------------------------------------

Citavi-Version: 5.7.1.0 (32 Bit)

Windows-Version: 10.0.19041.0

**Comment by Jay-Squared** [comment]
Ich fürchte, das werde ich nicht leisten können. Für Citavi 6 werde ich die letzte lauffähige Fassung archivieren, aber grundsätzlich entwickel ich das AddOn für die letzte mir zur Verfügung stehende Version (wenngleich im Moment mit etwas Rückstand). Die grundsätzliche Idee kann man ja anhand des Quellcodes nachvollziehen.
